name: CI for Portfolio

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest # Verwende eine Windows-Umgebung für die Builds

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Verwende die passende Node.js-Version
      - name: Install dependencies
        run: npm install
      - name: Run the build
        run: npm run build
      - name: Run tests
        run: npm test
